# Generated by Django 3.2.4 on 2021-07-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbooktitle',
            name='prim_topic_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
