# Generated by Django 3.2.4 on 2021-08-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0002_standardstrackinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='topictypes',
            name='description',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.CreateModel(
            name='multiSelectGS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.ManyToManyField(blank=True, related_name='select_grades', to='planit.gradeLevel')),
                ('subject', models.ManyToManyField(blank=True, related_name='select_subjects', to='planit.standardSubjects')),
            ],
        ),
    ]
