# Generated by Django 3.2.4 on 2021-07-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0002_textbooktitle_prim_topic_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='waitlistUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('grade_levels', models.CharField(max_length=100)),
                ('subjects', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='selectedactivity',
            name='demo_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
