# Generated by Django 3.2.4 on 2021-07-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0003_auto_20210724_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicinformation',
            name='topic_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
