# Generated by Django 3.2.4 on 2021-08-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0003_worksheetfull_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheetfull',
            name='week_of',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
