# Generated by Django 3.1.4 on 2021-01-10 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0003_lessontemplates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonproduct',
            old_name='blooms',
            new_name='topic_type',
        ),
    ]
