# Generated by Django 3.2.4 on 2021-08-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0004_worksheetfull_week_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksheetfull',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='worksheetfull',
            name='assigned_date',
        ),
        migrations.RemoveField(
            model_name='worksheetfull',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='worksheetfull',
            name='week_of',
        ),
        migrations.AddField(
            model_name='worksheetfull',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
