# Generated by Django 3.1.4 on 2021-08-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0004_auto_20210810_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentworksheetanswerfull',
            name='student_profile',
            field=models.ManyToManyField(blank=True, related_name='student_profile', to='planit.studentProfiles'),
        ),
    ]
