# Generated by Django 3.2.4 on 2021-07-24 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0004_topicinformation_topic_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='singleRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_score', models.IntegerField(blank=True, default=1, null=True)),
                ('single_rec_topics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.topicinformation')),
            ],
        ),
        migrations.AddField(
            model_name='reccomendedtopics',
            name='single_score',
            field=models.ManyToManyField(blank=True, null=True, to='planit.singleRec'),
        ),
    ]
