# Generated by Django 3.2.4 on 2021-08-16 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0004_auto_20210810_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='alertMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('html_message', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_alert', to=settings.AUTH_USER_MODEL)),
                ('sent_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recieved_alert', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
