# Generated by Django 3.1.4 on 2020-12-09 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0004_classroomsubjects_standardsubjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='singleStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_levels', models.ManyToManyField(blank=True, related_name='standards_grade', to='planit.gradeLevel')),
                ('standards_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.standardset')),
            ],
        ),
        migrations.CreateModel(
            name='lessonObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_title', models.CharField(max_length=200)),
                ('teacher_objective', models.CharField(max_length=1500)),
                ('lesson_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.classroom')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.classroomsubjects')),
            ],
        ),
    ]
