# Generated by Django 3.1.4 on 2021-01-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0004_auto_20210110_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonobjective',
            name='week_of',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
