# Generated by Django 3.1.4 on 2021-01-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0005_auto_20210111_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonobjective',
            name='objectives_topics',
            field=models.ManyToManyField(blank=True, null=True, related_name='objectives_topic', to='planit.topicInformation'),
        ),
    ]
