# Generated by Django 3.2.4 on 2021-07-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0005_auto_20210724_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlerec',
            name='sim_score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
