# Generated by Django 3.1.4 on 2020-12-09 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0005_lessonobjective_singlestandard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonobjective',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.standardsubjects'),
        ),
    ]
