# Generated by Django 3.1.4 on 2021-08-17 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0005_studentworksheetanswerfull_student_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentworksheetanswerfull',
            name='student_profile',
        ),
        migrations.AddField(
            model_name='studentworksheetanswerfull',
            name='student_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_info', to='planit.studentprofiles'),
        ),
    ]
