# Generated by Django 3.2.4 on 2021-08-09 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0005_auto_20210808_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheetclassassignment',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.academicyear'),
        ),
    ]
