# Generated by Django 3.2.4 on 2021-07-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0006_alter_singlerec_sim_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubesearchresult',
            name='transcript_text',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
