# Generated by Django 3.2.4 on 2021-08-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0006_worksheetclassassignment_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheettheme',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
