# Generated by Django 3.1.4 on 2020-12-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0006_auto_20201209_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonobjective',
            name='objectives_standards',
            field=models.ManyToManyField(blank=True, related_name='objectives_standards', to='planit.singleStandard'),
        ),
    ]
