# Generated by Django 3.1.4 on 2021-01-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0006_lessonobjective_objectives_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbookbackground',
            name='header',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='textbookbackground',
            name='section',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
