# Generated by Django 3.1.4 on 2021-08-17 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0005_alertmessage'),
        ('planit', '0006_auto_20210817_0449'),
    ]

    operations = [
    ]
