# Generated by Django 3.1.4 on 2020-12-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0007_lessonobjective_objectives_standards'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlestandard',
            name='standard_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='singlestandard',
            name='standard_identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='singlestandard',
            name='standard_objective',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
