# Generated by Django 3.2.4 on 2021-07-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0007_youtubesearchresult_transcript_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='youtubeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_id', models.CharField(max_length=1000)),
                ('line_num', models.IntegerField(blank=True, default=0, null=True)),
                ('transcript_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='youtubesearchresult',
            name='transcript_text',
        ),
        migrations.AddField(
            model_name='topicquestion',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicquestion',
            name='trans_line_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='youtubesearchresult',
            name='transcript_lines',
            field=models.ManyToManyField(blank=True, to='planit.youtubeLine'),
        ),
    ]
