# Generated by Django 3.2.4 on 2021-08-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0007_worksheettheme_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheettheme',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worksheettheme',
            name='is_seasonal',
            field=models.BooleanField(default=False),
        ),
    ]
