# Generated by Django 3.1.4 on 2021-08-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0007_merge_20210817_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonobjective',
            name='shared_classroom',
            field=models.ManyToManyField(blank=True, null=True, related_name='shared_classroom', to='planit.classroom'),
        ),
    ]
