# Generated by Django 3.1.4 on 2020-12-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0008_auto_20201209_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonobjective',
            name='week_of',
            field=models.CharField(default=32, max_length=10),
            preserve_default=False,
        ),
    ]
