# Generated by Django 3.1.4 on 2021-01-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0008_youtubesearchresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='shortStorySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('text', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='shortStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('story_image', models.ImageField(blank=True, null=True, upload_to='images/story/')),
                ('story_sections', models.ManyToManyField(blank=True, related_name='objectives_standards', to='planit.shortStorySection')),
            ],
        ),
    ]
