# Generated by Django 3.2.4 on 2021-08-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0008_auto_20210809_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheettheme',
            name='background_color',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
