# Generated by Django 3.1.4 on 2021-01-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0009_shortstory_shortstorysection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessontemplates',
            name='components',
        ),
        migrations.AddField(
            model_name='lessontemplates',
            name='components',
            field=models.ManyToManyField(blank=True, to='planit.topicTypes'),
        ),
    ]
