# Generated by Django 3.2.4 on 2021-08-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0009_worksheettheme_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheettheme',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
