# Generated by Django 3.1.4 on 2020-12-10 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0009_lessonobjective_week_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='weeklyObjectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_of', models.CharField(max_length=10)),
                ('objectives', models.ManyToManyField(blank=True, to='planit.lessonObjective')),
                ('subject_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.classroom')),
            ],
        ),
    ]
