# Generated by Django 3.1.4 on 2021-08-23 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0009_auto_20210819_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_user',
            name='user_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.userimageupload'),
        ),
    ]
