# Generated by Django 3.1.4 on 2021-08-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0010_school_user_user_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_user',
            name='teaching_experience',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
