# Generated by Django 3.1.4 on 2020-12-10 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0010_weeklyobjectives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlestandard',
            name='grade_levels',
        ),
        migrations.RemoveField(
            model_name='singlestandard',
            name='standard_category',
        ),
        migrations.AddField(
            model_name='singlestandard',
            name='competency',
            field=models.TextField(default='All', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singlestandard',
            name='skill_topic',
            field=models.TextField(default='All', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singlestandard',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.standardsubjects'),
        ),
        migrations.AlterField(
            model_name='singlestandard',
            name='standard_objective',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
