# Generated by Django 3.2.4 on 2021-08-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0010_alter_lessontemplates_ks_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlerelatedquestions',
            name='relevance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
