# Generated by Django 3.1.4 on 2021-01-17 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0010_auto_20210117_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessontemplates',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.shortstory'),
        ),
    ]
