# Generated by Django 3.2.4 on 2021-08-04 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0011_googlerelatedquestions_relevance'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherInvitations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_ref', models.CharField(blank=True, max_length=255, null=True, verbose_name='Teacher Reference')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_pending', models.BooleanField(default=True)),
                ('is_waitlist', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by1', to=settings.AUTH_USER_MODEL)),
                ('for_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.classroom')),
                ('new_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_user1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
