# Generated by Django 3.2.4 on 2021-08-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0011_googlerelatedquestions_relevance'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinvitation',
            name='is_waitlist',
            field=models.BooleanField(default=False),
        ),
    ]
