# Generated by Django 3.2.4 on 2021-08-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0012_teacherinvitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='reccomendedtopics',
            name='searched_level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
