# Generated by Django 3.1.4 on 2020-12-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0012_singlestandard_grade_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='vocabularyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('p_o_s', models.CharField(blank=True, max_length=50, null=True)),
                ('definition', models.CharField(blank=True, max_length=500, null=True)),
                ('sentence', models.CharField(blank=True, max_length=300, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='images/words/')),
            ],
        ),
    ]
