# Generated by Django 3.1.4 on 2021-08-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0012_auto_20210823_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedactivity',
            name='standard_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
