# Generated by Django 3.1.4 on 2021-01-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0013_youtubesearchresult_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikitopic',
            name='term',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
