# Generated by Django 3.2.4 on 2021-08-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0013_reccomendedtopics_searched_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicdescription',
            name='is_gen',
            field=models.BooleanField(default=False),
        ),
    ]
