# Generated by Django 3.1.4 on 2021-01-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0014_wikitopic_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='topicDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='topicinformation',
            name='description',
        ),
        migrations.AddField(
            model_name='topicinformation',
            name='description',
            field=models.ManyToManyField(blank=True, to='planit.topicDescription'),
        ),
    ]
