# Generated by Django 3.2.4 on 2021-08-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0014_topicdescription_is_gen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlerec',
            name='sim_score',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
