# Generated by Django 3.1.4 on 2020-12-10 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0015_lessonfull_lessonsection_mainquestion_questionlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='bloomsLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('group', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='learningStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('group', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='lessonfull',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.standardsubjects'),
        ),
        migrations.AddField(
            model_name='lessonfull',
            name='blooms',
            field=models.ManyToManyField(blank=True, to='planit.bloomsLevel'),
        ),
        migrations.AddField(
            model_name='lessonfull',
            name='styles',
            field=models.ManyToManyField(blank=True, to='planit.learningStyle'),
        ),
    ]
