# Generated by Django 3.1.4 on 2021-01-21 21:22

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0015_auto_20210121_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='lessonText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
    ]
