# Generated by Django 3.2.4 on 2021-08-04 21:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0016_lessontemplates_single_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbooktitle',
            name='wiki_page',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
