# Generated by Django 3.2.4 on 2021-08-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0017_textbooktitle_wiki_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbookbackground',
            name='term_created',
            field=models.BooleanField(default=False),
        ),
    ]
