# Generated by Django 3.1.4 on 2021-01-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0017_lessontext_matched_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessontext',
            name='is_initial',
            field=models.BooleanField(default=False),
        ),
    ]
