# Generated by Django 3.1.4 on 2020-12-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0018_teacherlessontemplates'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonobjective',
            name='is_skill',
            field=models.BooleanField(default=False),
        ),
    ]
