# Generated by Django 3.1.4 on 2021-01-22 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0019_auto_20210122_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='questionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='storyFull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='storySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=1000, null=True)),
                ('Section', models.CharField(blank=True, max_length=10000, null=True)),
                ('Section_Image', models.ImageField(blank=True, null=True, upload_to='images/story/')),
            ],
        ),
        migrations.CreateModel(
            name='topicQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=200, null=True)),
                ('question_points', models.IntegerField(blank=True, default=1, null=True)),
                ('Question', models.CharField(blank=True, max_length=1000, null=True)),
                ('Question_Image', models.ImageField(blank=True, null=True, upload_to='images/question/')),
                ('Correct', models.CharField(blank=True, max_length=500, null=True)),
                ('correct_image', models.ImageField(blank=True, null=True, upload_to='images/question/')),
                ('Incorrect_One', models.CharField(blank=True, max_length=500, null=True)),
                ('in_one_image', models.ImageField(blank=True, null=True, upload_to='images/question/')),
                ('Incorrect_Two', models.CharField(blank=True, max_length=500, null=True)),
                ('in_two_image', models.ImageField(blank=True, null=True, upload_to='images/question/')),
                ('Incorrect_Three', models.CharField(blank=True, max_length=500, null=True)),
                ('in_three_image', models.ImageField(blank=True, null=True, upload_to='images/question/')),
                ('explanation', models.CharField(blank=True, max_length=1000, null=True)),
                ('grade_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.gradelevel')),
                ('question_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.questiontype')),
                ('standard_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.standardset')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.standardsubjects')),
                ('topic_story', models.ManyToManyField(blank=True, to='planit.storyFull')),
                ('topic_type', models.ManyToManyField(blank=True, to='planit.topicTypes')),
            ],
        ),
        migrations.AddField(
            model_name='topicinformation',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/topic/'),
        ),
        migrations.CreateModel(
            name='worksheetSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(blank=True, max_length=200, null=True)),
                ('directions', models.CharField(blank=True, max_length=1000, null=True)),
                ('section_image', models.ImageField(blank=True, null=True, upload_to='images/question/')),
                ('questions', models.ManyToManyField(blank=True, to='planit.topicQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='worksheetFull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('worksheet_image', models.ImageField(blank=True, null=True, upload_to='images/question/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(blank=True, to='planit.topicQuestion')),
            ],
        ),
        migrations.AddField(
            model_name='storyfull',
            name='section',
            field=models.ManyToManyField(blank=True, to='planit.storySection'),
        ),
    ]
