# Generated by Django 3.1.4 on 2020-12-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0019_lessonobjective_is_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonobjective',
            name='objective_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lessonobjective',
            name='teacher_objective',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='lessonobjective',
            name='week_of',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
