# Generated by Django 3.1.4 on 2020-12-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0020_auto_20201214_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonobjective',
            name='objectives_standards',
            field=models.ManyToManyField(blank=True, null=True, related_name='objectives_standards', to='planit.singleStandard'),
        ),
    ]
