# Generated by Django 3.2.4 on 2021-08-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0020_auto_20210805_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedactivity',
            name='bl_labels',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='selectedactivity',
            name='colors',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='selectedactivity',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selectedactivity',
            name='mi_icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='selectedactivity',
            name='mi_labels',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
