# Generated by Django 3.1.4 on 2021-01-24 16:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0020_auto_20210122_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessontext',
            name='content2',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessontext',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
