# Generated by Django 3.1.4 on 2021-01-24 19:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0021_auto_20210124_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessontext',
            old_name='content',
            new_name='activities',
        ),
        migrations.RenameField(
            model_name='lessontext',
            old_name='content2',
            new_name='lesson_terms',
        ),
        migrations.AddField(
            model_name='lessontext',
            name='overviwe',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
