# Generated by Django 3.2.4 on 2021-08-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0021_auto_20210806_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectedactivity',
            old_name='colors',
            new_name='bl_color',
        ),
        migrations.AddField(
            model_name='selectedactivity',
            name='mi_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
