# Generated by Django 3.1.4 on 2020-12-14 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0021_auto_20201214_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='lessonStandardRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=False)),
                ('lesson_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.classroom')),
                ('objectives_standards', models.ManyToManyField(blank=True, null=True, related_name='rec_standards', to='planit.singleStandard')),
            ],
        ),
    ]
