# Generated by Django 3.1.4 on 2021-01-24 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0022_auto_20210124_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessontext',
            old_name='overviwe',
            new_name='overview',
        ),
    ]
