# Generated by Django 3.2.4 on 2021-08-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0022_auto_20210806_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheetfull',
            name='key_terms',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
