# Generated by Django 3.1.4 on 2020-12-14 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0022_lessonstandardrecommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonstandardrecommendation',
            name='objectives_standards',
        ),
        migrations.AddField(
            model_name='lessonstandardrecommendation',
            name='objectives_standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.singlestandard'),
        ),
    ]
