# Generated by Django 3.1.4 on 2021-01-27 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0023_auto_20210124_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='selectedActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_text', models.CharField(blank=True, max_length=1500, null=True)),
                ('verb', models.CharField(blank=True, max_length=100, null=True)),
                ('work_product', models.CharField(blank=True, max_length=300, null=True)),
                ('bloom', models.IntegerField(blank=True, default=0, null=True)),
                ('mi', models.IntegerField(blank=True, default=0, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lesson_overview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.lessonobjective')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.shortstory')),
            ],
        ),
    ]
