# Generated by Django 3.2.4 on 2021-08-06 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0023_worksheetfull_key_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheetfull',
            name='grade_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.gradelevel'),
        ),
        migrations.AddField(
            model_name='worksheetfull',
            name='standards_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.standardset'),
        ),
        migrations.AddField(
            model_name='worksheetfull',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.standardsubjects'),
        ),
    ]
