# Generated by Django 3.1.4 on 2020-12-15 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0024_lessonstandardrecommendation_objectives'),
    ]

    operations = [
        migrations.CreateModel(
            name='googleSearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=500)),
                ('snippet', models.CharField(max_length=1000)),
                ('lesson_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.lessonobjective')),
            ],
        ),
        migrations.CreateModel(
            name='googleRelatedQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=False)),
                ('question', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
                ('snippet', models.CharField(max_length=1000)),
                ('lesson_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.lessonobjective')),
            ],
        ),
    ]
