# Generated by Django 3.1.4 on 2021-01-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0024_selectedactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedactivity',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
