# Generated by Django 3.2.4 on 2021-08-06 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0026_rename_key_terms_worksheetfull_ws_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimageupload',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userimageupload',
            name='uploaded_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
