# Generated by Django 3.1.4 on 2021-01-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0026_lessontext_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicquestion',
            name='Correct',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='topicquestion',
            name='Incorrect_One',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='topicquestion',
            name='Incorrect_Three',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='topicquestion',
            name='Incorrect_Two',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='topicquestion',
            name='Question',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='topicquestion',
            name='explanation',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
