# Generated by Django 3.1.4 on 2021-01-29 16:35

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0027_auto_20210129_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='US'),
        ),
    ]
