# Generated by Django 3.1.4 on 2020-12-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0027_wikitopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikitopic',
            name='relevance',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
