# Generated by Django 3.2.4 on 2021-08-06 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0027_auto_20210806_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicquestion',
            name='Question_Image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_image', to='planit.userimageupload'),
        ),
        migrations.AlterField(
            model_name='topicquestion',
            name='correct_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correct_image', to='planit.userimageupload'),
        ),
        migrations.AlterField(
            model_name='topicquestion',
            name='in_one_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Incorrect_One_image', to='planit.userimageupload'),
        ),
        migrations.AlterField(
            model_name='topicquestion',
            name='in_three_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Incorrect_Three_image', to='planit.userimageupload'),
        ),
        migrations.AlterField(
            model_name='topicquestion',
            name='in_two_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Incorrect_Two_image', to='planit.userimageupload'),
        ),
        migrations.AlterField(
            model_name='worksheetfull',
            name='worksheet_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worksheet_image', to='planit.userimageupload'),
        ),
    ]
