# Generated by Django 3.1.4 on 2021-01-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0028_auto_20210129_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
