# Generated by Django 3.2.4 on 2021-08-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0028_auto_20210806_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimageupload',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
