# Generated by Django 3.1.4 on 2020-12-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0028_wikitopic_relevance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikitopic',
            name='relevance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
