# Generated by Django 3.1.4 on 2021-01-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0029_auto_20210129_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_grade', models.CharField(blank=True, max_length=100, null=True)),
                ('current_state', models.CharField(blank=True, max_length=100, null=True)),
                ('current_planning', models.TextField(blank=True, max_length=1000, null=True)),
                ('happy_scale', models.CharField(blank=True, max_length=50, null=True)),
                ('lesson_good', models.TextField(blank=True, max_length=1000, null=True)),
                ('lesson_bad', models.TextField(blank=True, max_length=1000, null=True)),
                ('ideal_feature', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
