# Generated by Django 3.1.4 on 2020-12-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0029_auto_20201215_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordresults',
            name='relevance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
