# Generated by Django 3.1.4 on 2021-02-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0030_teacherquestionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbookbackground',
            name='line_lemma',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='textbookbackground',
            name='line_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
