# Generated by Django 3.1.4 on 2021-02-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0031_auto_20210208_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicinformation',
            name='text_index',
            field=models.ManyToManyField(blank=True, to='planit.textBookBackground'),
        ),
    ]
