# Generated by Django 3.1.4 on 2021-02-14 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0032_topicinformation_text_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_user',
            name='standards_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.standardset'),
        ),
    ]
