# Generated by Django 3.1.4 on 2021-02-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0033_school_user_standards_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='planit.standardSubjects'),
        ),
        migrations.DeleteModel(
            name='classroomSubjects',
        ),
    ]
