# Generated by Django 3.1.4 on 2021-02-19 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0034_auto_20210214_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='lessonImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_image', models.ImageField(blank=True, null=True, upload_to='images/words/')),
                ('content', models.CharField(blank=True, max_length=2000, null=True)),
                ('matched_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.lessonobjective')),
            ],
        ),
    ]
