# Generated by Django 3.1.4 on 2021-02-19 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0035_lessonimageupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='lessonPDFImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_image', models.ImageField(blank=True, null=True, upload_to='images/words/')),
                ('matched_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.lessonobjective')),
            ],
        ),
        migrations.CreateModel(
            name='lessonPDFText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_doc', models.FileField(blank=True, null=True, upload_to='file/')),
                ('content', models.CharField(blank=True, max_length=2000, null=True)),
                ('matched_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.lessonobjective')),
                ('pdf_images', models.ManyToManyField(blank=True, to='planit.lessonPDFImage')),
            ],
        ),
    ]
