# Generated by Django 3.1.4 on 2021-02-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0036_lessonpdfimage_lessonpdftext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpdftext',
            name='content',
            field=models.CharField(blank=True, max_length=25000, null=True),
        ),
    ]
