# Generated by Django 3.1.4 on 2021-02-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0037_auto_20210222_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningDemonstration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='lessonobjective',
            name='objectives_demonstration',
            field=models.ManyToManyField(blank=True, null=True, related_name='objectives_demonstration', to='planit.LearningDemonstration'),
        ),
    ]
