# Generated by Django 3.1.4 on 2021-03-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0038_auto_20210225_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicquestion',
            name='Question',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
