# Generated by Django 3.1.4 on 2021-03-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0042_topicquestion_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbookbackground',
            name='page_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='textbooktitle',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
