# Generated by Django 3.1.4 on 2021-03-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0043_auto_20210307_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessontemplates',
            name='ks_demo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
