# Generated by Django 3.1.4 on 2021-03-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0044_lessontemplates_ks_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessontemplates',
            name='grouping',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
