# Generated by Django 3.1.4 on 2021-03-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0046_selectedactivity_ks_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningDemonstrationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('topic_type', models.ManyToManyField(blank=True, to='planit.topicTypes')),
            ],
        ),
    ]
