# Generated by Django 3.1.4 on 2021-03-08 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0047_learningdemonstrationtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningdemonstration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningdemonstration',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
