# Generated by Django 3.1.4 on 2021-03-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0048_auto_20210308_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessontext',
            name='is_multi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessontext',
            name='is_plural',
            field=models.BooleanField(default=False),
        ),
    ]
