# Generated by Django 3.1.4 on 2021-03-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0049_auto_20210311_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessontemplates',
            name='is_multi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessontemplates',
            name='is_plural',
            field=models.BooleanField(default=False),
        ),
    ]
