# Generated by Django 3.1.4 on 2021-03-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0050_auto_20210311_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningdemonstration',
            name='topic_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
