# Generated by Django 3.1.4 on 2021-03-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0052_selectedactivity_template_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicquestion',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topicquestion',
            name='original_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
