# Generated by Django 3.1.4 on 2021-03-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0055_auto_20210326_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofiles',
            name='student_pin',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
