# Generated by Django 3.1.4 on 2021-05-03 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0056_studentprofiles_student_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicdescription',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topicdescription',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
