# Generated by Django 3.1.4 on 2021-05-08 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0057_auto_20210503_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='matchedTopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_overview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.lessonobjective')),
                ('objectives_topics', models.ManyToManyField(blank=True, null=True, related_name='objectives_activity_topic', to='planit.topicInformation')),
            ],
        ),
    ]
