# Generated by Django 3.1.4 on 2021-05-13 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0061_topicdescription_topic_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='userImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('uploaded_image', models.ImageField(blank=True, null=True, upload_to='images/question/')),
            ],
        ),
        migrations.CreateModel(
            name='userNickname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('is_firstname', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='worksheetTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.CharField(blank=True, max_length=12, null=True)),
                ('secondary', models.CharField(blank=True, max_length=12, null=True)),
                ('link', models.CharField(blank=True, max_length=12, null=True)),
                ('backgroun_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_image', to='planit.userimageupload')),
                ('first_name', models.ManyToManyField(blank=True, related_name='first_name', to='planit.userNickname')),
                ('last_name', models.ManyToManyField(blank=True, related_name='last_name', to='planit.userNickname')),
                ('questions', models.ManyToManyField(blank=True, related_name='icon_image', to='planit.userImageUpload')),
            ],
        ),
        migrations.AddField(
            model_name='worksheetfull',
            name='worksheet_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planit.worksheettheme'),
        ),
    ]
