# Generated by Django 3.1.4 on 2021-05-13 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0062_auto_20210513_0211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksheettheme',
            old_name='backgroun_image',
            new_name='background_image',
        ),
        migrations.RenameField(
            model_name='worksheettheme',
            old_name='questions',
            new_name='icon_image',
        ),
        migrations.AddField(
            model_name='worksheettheme',
            name='demo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demo_image', to='planit.userimageupload'),
        ),
    ]
