# Generated by Django 3.1.4 on 2021-05-14 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0063_auto_20210513_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=200, null=True)),
                ('question', models.CharField(blank=True, max_length=200, null=True)),
                ('corrrect', models.CharField(blank=True, max_length=200, null=True)),
                ('answer', models.CharField(blank=True, max_length=200, null=True)),
                ('is_graded', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('question_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planit.topicquestion')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('worksheet_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planit.worksheetfull')),
            ],
        ),
        migrations.CreateModel(
            name='studentWorksheetAnswerFull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=200, null=True)),
                ('is_graded', models.BooleanField(default=False)),
                ('is_passing', models.BooleanField(default=False)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student_answers', models.ManyToManyField(blank=True, null=True, related_name='student_answers', to='planit.studentQuestionAnswer')),
                ('worksheet_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planit.worksheetfull')),
            ],
        ),
    ]
