# Generated by Django 3.1.4 on 2021-05-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0064_studentquestionanswer_studentworksheetanswerfull'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentquestionanswer',
            old_name='corrrect',
            new_name='correct',
        ),
    ]
