# Generated by Django 3.1.4 on 2021-05-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0065_auto_20210514_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentworksheetanswerfull',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
