# Generated by Django 3.1.4 on 2021-05-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0068_classroomlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomlist',
            name='academic_year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
