# Generated by Django 3.1.4 on 2021-05-24 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0068_auto_20210524_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='classroomLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, default=0, null=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.academicyear')),
                ('lesson_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.classroom')),
                ('students', models.ManyToManyField(blank=True, null=True, related_name='classroom_students', to='planit.studentProfiles')),
            ],
        ),
    ]
