# Generated by Django 3.1.4 on 2021-05-28 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0069_classroomlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='single_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_grade', to='planit.gradelevel'),
        ),
        migrations.AddField(
            model_name='lessonobjective',
            name='current_grade_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.gradelevel'),
        ),
        migrations.AddField(
            model_name='lessontemplates',
            name='current_grade_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.gradelevel'),
        ),
        migrations.AddField(
            model_name='lessontemplates',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.standardsubjects'),
        ),
    ]
