# Generated by Django 3.1.4 on 2021-05-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0070_auto_20210523_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentworksheetanswerfull',
            name='assignment_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
