# Generated by Django 3.1.4 on 2021-05-28 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0070_auto_20210528_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessontemplates',
            old_name='current_grade_level',
            new_name='grade_level',
        ),
        migrations.AddField(
            model_name='learningdemonstrationtemplate',
            name='grade_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.gradelevel'),
        ),
        migrations.AddField(
            model_name='learningdemonstrationtemplate',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.standardsubjects'),
        ),
    ]
