# Generated by Django 3.1.4 on 2021-05-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0071_auto_20210528_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningdemonstrationtemplate',
            name='is_multi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningdemonstrationtemplate',
            name='is_plural',
            field=models.BooleanField(default=False),
        ),
    ]
