# Generated by Django 3.1.4 on 2021-05-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0072_auto_20210528_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicinformation',
            name='from_wiki',
            field=models.BooleanField(default=False),
        ),
    ]
