# Generated by Django 3.1.4 on 2021-05-23 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0072_auto_20210523_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentpraise',
            old_name='due_date',
            new_name='sent_date',
        ),
    ]
