# Generated by Django 3.1.4 on 2021-05-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0073_auto_20210523_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpraise',
            name='week_of',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
