# Generated by Django 3.1.4 on 2021-06-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0073_topicinformation_from_wiki'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicinformation',
            name='is_secondary',
            field=models.BooleanField(default=False),
        ),
    ]
