# Generated by Django 3.1.4 on 2021-06-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0074_topicinformation_is_secondary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonstandardrecommendation',
            name='objectives_standard',
        ),
        migrations.AddField(
            model_name='lessonstandardrecommendation',
            name='objectives_standard',
            field=models.ManyToManyField(blank=True, to='planit.singleStandard'),
        ),
    ]
