# Generated by Django 3.1.4 on 2021-05-24 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0075_auto_20210524_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpraise',
            name='week_of',
        ),
    ]
