# Generated by Django 3.1.4 on 2021-05-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0076_remove_studentpraise_week_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpraise',
            name='week_of',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
