# Generated by Django 3.1.4 on 2021-06-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0076_selectedactivity_objectives_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedactivity',
            name='ret_rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
