# Generated by Django 3.1.4 on 2021-05-24 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0077_studentpraise_week_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroomlist',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='classroomlist',
            name='year',
        ),
    ]
