# Generated by Django 3.1.4 on 2021-06-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0077_selectedactivity_ret_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicinformation',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
