# Generated by Django 3.1.4 on 2021-06-05 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0078_topicinformation_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='removedTopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.lessonobjective')),
                ('objectives_topics', models.ManyToManyField(blank=True, null=True, related_name='removed_topics', to='planit.topicInformation')),
            ],
        ),
    ]
