# Generated by Django 3.2.4 on 2021-06-28 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0080_auto_20210605_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikitopic',
            name='textbook_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planit.textbooktitle'),
        ),
    ]
