# Generated by Django 3.2.4 on 2021-07-08 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0082_studentinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinvitation',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentinvitation',
            name='student_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planit.studentprofiles'),
        ),
        migrations.AddField(
            model_name='textbooktitle',
            name='wiki_page',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
