# Generated by Django 3.2.4 on 2021-07-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0083_auto_20210708_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbookbackground',
            name='term_created',
            field=models.BooleanField(default=False),
        ),
    ]
