# Generated by Django 3.2.4 on 2021-07-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0085_lessonobjective_standard_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicdescription',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
    ]
