# Generated by Django 3.2.4 on 2021-07-13 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0086_topicdescription_is_generated'),
    ]

    operations = [
        
    ]
