# Generated by Django 3.2.4 on 2021-07-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0087_studentinvitation_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
