# Generated by Django 3.2.4 on 2021-07-18 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0088_user_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reccomendedtopics',
            name='search_level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        
    ]
