import random
from .generator import *
from .models import * 
first_names = ['Mauve',
                'Red',
                'Blue',
                'Green',
                'Orange',
                'White',
                'Black',
                'Brown',
                'Yellow',
                'Bronze',
                'Golden',
                'Purple',
                'Grey',
                'Khaki',
                'Plum',
                'Lime',
                'Navy',
                'Tan',
                'Maroon',
                'Emerald',
                'Beige',
                'Fawn',
                'Cactus',
                'Plum',
                'Silver',
                'Turquoise',
                'Mustard',
                'Coral',
                'Pink',
                'Aqua',
                'adorable',
                'adventurous',
                'alert',
                'annoying',
                'angry',
                'anxious',
                'agressive',
                'scary',
                'arrogant',
                'attractive',
                'beautiful',
                'bloody',
                'brainy',
                'brave',
                'clumsy',
                'charming',
                'clever',
                'crazy',
                'creepy',
                'dangerous',
                'eager',
                'easy',
                'enthusiastic',
                'energetic',
                'fancy',
                'funny',
                'hungry',
                'itchy',
                'Curious']

second_names = ['Mercury',
                'Venus',
                'Earth',
                'Mars',
                'Jupiter',
                'Saturn',
                'Uranus',
                'Pluto',
                'Naptune',
                'Galaxy',
                'Axis',
                'Lunar',
                'Milkyway',
                'Star',
                'Moon',
                'Eclipse',
                'Cosmos',
                'Solar',
                'World',
                'Creation',
                'Space',
                'Heaven',
                'Ocean',
                'Globe',
                'Sphere',
                'Planet',
                'Sun',
                'Sky',
                'Infinity',
                'Satellite']


def build_username():
    first_name = random.choice(first_names).capitalize() 
    second_name = random.choice(second_names)

    token_number = token_generator.make_token(8)
    user_name = first_name + second_name[0] + token_number
    password = token_generator.make_token(8)
    result = {'first_name': first_name, 'last_name': second_name, 'user_name': user_name, 'raw_password': password}
    return(result)